package de.balticsoftware.cons;

public class TrelloMock {

    public static final String AC_BOARD_WELCOME = "{\"name\":\"Willkommens-Board\",\"desc\":\"\",\"descData\":null,\"closed\":false,\"idOrganization\":null,\"limits\":null,\"pinned\":null,\"invitations\":null,\"shortLink\":\"vpFSM0H5\",\"powerUps\":[],\"dateLastActivity\":\"2018-02-11T12:00:33.058Z\",\"idTags\":[],\"datePluginDisable\":null,\"id\":\"5a803060a8bc7d680ca44c39\",\"invited\":false,\"starred\":false,\"url\":\"https://trello.com/b/vpFSM0H5/willkommens-board\",\"prefs\":{\"permissionLevel\":\"private\",\"voting\":\"disabled\",\"comments\":\"members\",\"invitations\":\"members\",\"selfJoin\":true,\"cardCovers\":true,\"calendarFeedEnabled\":false,\"background\":\"lime\",\"backgroundImage\":null,\"backgroundImageScaled\":null,\"backgroundTile\":false,\"backgroundBrightness\":\"dark\",\"backgroundColor\":\"#4BBF6B\",\"backgroundBottomColor\":\"#4BBF6B\",\"backgroundTopColor\":\"#4BBF6B\",\"canBePublic\":true,\"canBeOrg\":true,\"canBePrivate\":true,\"canInvite\":true},\"subscribed\":false,\"labelNames\":{\"green\":\"\",\"yellow\":\"\",\"orange\":\"\",\"red\":\"\",\"purple\":\"\",\"blue\":\"\",\"sky\":\"\",\"lime\":\"\",\"pink\":\"\",\"black\":\"\"},\"dateLastView\":\"2018-02-11T12:24:42.212Z\",\"shortUrl\":\"https://trello.com/b/vpFSM0H5\",\"memberships\":[{\"id\":\"5a803060a8bc7d680ca44c3c\",\"idMember\":\"4e6a7fad05d98b02ba00845c\",\"memberType\":\"normal\",\"unconfirmed\":false,\"deactivated\":false},{\"id\":\"5a803060a8bc7d680ca44c3d\",\"idMember\":\"5a803060a8bc7d680ca44c36\",\"memberType\":\"admin\",\"unconfirmed\":false,\"deactivated\":false}]}";
    public static final String AC_BOARD_API_TEST_BOARD = "{\"name\":\"API Test Board\",\"desc\":\"\",\"descData\":null,\"closed\":false,\"idOrganization\":null,\"limits\":null,\"pinned\":null,\"invitations\":null,\"shortLink\":\"q6VTqs9o\",\"powerUps\":[],\"dateLastActivity\":null,\"idTags\":[],\"datePluginDisable\":null,\"id\":\"5a80306437896192ef3e150e\",\"invited\":false,\"starred\":false,\"url\":\"https://trello.com/b/q6VTqs9o/api-test-board\",\"prefs\":{\"permissionLevel\":\"private\",\"voting\":\"disabled\",\"comments\":\"members\",\"invitations\":\"members\",\"selfJoin\":true,\"cardCovers\":true,\"cardAging\":\"regular\",\"calendarFeedEnabled\":false,\"background\":\"blue\",\"backgroundImage\":null,\"backgroundImageScaled\":null,\"backgroundTile\":false,\"backgroundBrightness\":\"dark\",\"backgroundColor\":\"#0079BF\",\"backgroundBottomColor\":\"#0079BF\",\"backgroundTopColor\":\"#0079BF\",\"canBePublic\":true,\"canBeOrg\":true,\"canBePrivate\":true,\"canInvite\":true},\"subscribed\":false,\"labelNames\":{\"green\":\"\",\"yellow\":\"\",\"orange\":\"\",\"red\":\"\",\"purple\":\"\",\"blue\":\"\",\"sky\":\"\",\"lime\":\"\",\"pink\":\"\",\"black\":\"\"},\"dateLastView\":\"2018-02-11T12:24:42.215Z\",\"shortUrl\":\"https://trello.com/b/q6VTqs9o\",\"memberships\":[{\"id\":\"5a80306437896192ef3e150f\",\"idMember\":\"5a803060a8bc7d680ca44c36\",\"memberType\":\"admin\",\"unconfirmed\":false,\"deactivated\":false}]}";
    public static final String AC_BOARDS = "[" + AC_BOARD_WELCOME + " ," + AC_BOARD_API_TEST_BOARD + "]";

}
